# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Seazoned' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire'
	pod 'SwiftyJSON'
	pod 'ReachabilitySwift'
	pod 'Kingfisher'
	pod 'SVProgressHUD'
	pod 'GooglePlacesSearchController'
	pod 'FacebookCore'
    pod 'Firebase/Storage'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'Firebase/RemoteConfig'
    pod 'Firebase/Messaging'
    pod 'Firebase/Core'
    pod 'GooglePlaces'
    pod 'GooglePlacePicker'
    pod 'GoogleMaps'
    pod 'OAuthSwift'

  pod 'JSQMessagesViewController'
pod "ImageSlideshow/Kingfisher"
pod 'FacebookLogin'
pod ‘Google/SignIn’
pod 'SANotificationViews'

  # Pods for Seazoned

end
